// Generated by gencpp from file my_slam_interfaces/LandmarkArray.msg
// DO NOT EDIT!


#ifndef MY_SLAM_INTERFACES_MESSAGE_LANDMARKARRAY_H
#define MY_SLAM_INTERFACES_MESSAGE_LANDMARKARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <my_slam_interfaces/Landmark.h>

namespace my_slam_interfaces
{
template <class ContainerAllocator>
struct LandmarkArray_
{
  typedef LandmarkArray_<ContainerAllocator> Type;

  LandmarkArray_()
    : header()
    , landmarks()  {
    }
  LandmarkArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::my_slam_interfaces::Landmark_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::my_slam_interfaces::Landmark_<ContainerAllocator> >> _landmarks_type;
  _landmarks_type landmarks;





  typedef boost::shared_ptr< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> const> ConstPtr;

}; // struct LandmarkArray_

typedef ::my_slam_interfaces::LandmarkArray_<std::allocator<void> > LandmarkArray;

typedef boost::shared_ptr< ::my_slam_interfaces::LandmarkArray > LandmarkArrayPtr;
typedef boost::shared_ptr< ::my_slam_interfaces::LandmarkArray const> LandmarkArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator1> & lhs, const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.landmarks == rhs.landmarks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator1> & lhs, const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_slam_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f50d5bcb520887abb25781659852ffdf";
  }

  static const char* value(const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf50d5bcb520887abULL;
  static const uint64_t static_value2 = 0xb25781659852ffdfULL;
};

template<class ContainerAllocator>
struct DataType< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_slam_interfaces/LandmarkArray";
  }

  static const char* value(const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Landmark[] landmarks\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: my_slam_interfaces/Landmark\n"
"float32 x\n"
"float32 y\n"
"float32 radius\n"
"int32 id\n"
;
  }

  static const char* value(const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandmarkArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_slam_interfaces::LandmarkArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_slam_interfaces::LandmarkArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "landmarks: ";
    if (v.landmarks.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::my_slam_interfaces::Landmark_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.landmarks[i]);
    }
    if (v.landmarks.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SLAM_INTERFACES_MESSAGE_LANDMARKARRAY_H
