// Generated by gencpp from file my_slam_interfaces/Ticks.msg
// DO NOT EDIT!


#ifndef MY_SLAM_INTERFACES_MESSAGE_TICKS_H
#define MY_SLAM_INTERFACES_MESSAGE_TICKS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_slam_interfaces
{
template <class ContainerAllocator>
struct Ticks_
{
  typedef Ticks_<ContainerAllocator> Type;

  Ticks_()
    : header()
    , left_ticks(0)
    , right_ticks(0)  {
    }
  Ticks_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_ticks(0)
    , right_ticks(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _left_ticks_type;
  _left_ticks_type left_ticks;

   typedef int64_t _right_ticks_type;
  _right_ticks_type right_ticks;





  typedef boost::shared_ptr< ::my_slam_interfaces::Ticks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_slam_interfaces::Ticks_<ContainerAllocator> const> ConstPtr;

}; // struct Ticks_

typedef ::my_slam_interfaces::Ticks_<std::allocator<void> > Ticks;

typedef boost::shared_ptr< ::my_slam_interfaces::Ticks > TicksPtr;
typedef boost::shared_ptr< ::my_slam_interfaces::Ticks const> TicksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_slam_interfaces::Ticks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_slam_interfaces::Ticks_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_slam_interfaces::Ticks_<ContainerAllocator1> & lhs, const ::my_slam_interfaces::Ticks_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_ticks == rhs.left_ticks &&
    lhs.right_ticks == rhs.right_ticks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_slam_interfaces::Ticks_<ContainerAllocator1> & lhs, const ::my_slam_interfaces::Ticks_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_slam_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_slam_interfaces::Ticks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_slam_interfaces::Ticks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_slam_interfaces::Ticks_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2e3ba80aef7601eec29b4f6edd523f2";
  }

  static const char* value(const ::my_slam_interfaces::Ticks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2e3ba80aef7601eULL;
  static const uint64_t static_value2 = 0xec29b4f6edd523f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_slam_interfaces/Ticks";
  }

  static const char* value(const ::my_slam_interfaces::Ticks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int64 left_ticks\n"
"int64 right_ticks\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_slam_interfaces::Ticks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_ticks);
      stream.next(m.right_ticks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ticks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_slam_interfaces::Ticks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_slam_interfaces::Ticks_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_ticks: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left_ticks);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_ticks: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right_ticks);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SLAM_INTERFACES_MESSAGE_TICKS_H
